name = input('Enter your name:')
age=input('How old are you:')
print(f'Привіт,{name},тобі зараз {age} років.')
print('Привіт,{},тобі зараз {} років. '.format(name,age))
print('Привіт,'+ name + ',тобі зараз '+ age + ' років.')
